apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: maria-cm
data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: maria-sts-test-test
  name: maria-sts-test-test
spec:
  serviceName: maria-svc
  volumeClaimTemplates:
  - metadata:
     name: maria-50m-pvc
    spec:
     storageClassName: nfs-client
     accessModes:
       - ReadWriteMany
     resources:
       requests:
        storage: 100Mi                             
  replicas: 1
  selector:
    matchLabels:
      app: maria-sts-test-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maria-sts-test-test
    spec:
      containers:
      - image: mariadb:10
        name: mariadb
        ports:
        - containerPort: 3306
        envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
           name: maria-cm
        volumeMounts:
        - name: maria-50m-pvc
          mountPath: /var/lib/mysql
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: maria-sts-test-test
  name: maria-svc

spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: maria-sts-test-test
