apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-500m-pv

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi

  nfs:
    path: /tmp/nfs/500M-pv
    server: 192.168.186.135